theme: material
site_name: Ponzu
docs_dir: src
site_dir: build
repo_name: sdassow/ponzu
repo_url: https://github.com/sdassow/ponzu

markdown_extensions:
      - codehilite(linenums=false)
      - meta
      - admonition
      - toc(permalink=true)

google_analytics:
      - 'UA-98609560-1'
      - auto

extra:
  palette:
    primary: grey
    accent: light-blue
  social:
    - type: github
      link: https://github.com/sdassow
  logo: images/logo.png
